name: Android CI

on: 
  push:
    branches:
      - dev  # branch name
  pull_request:
    branches:
      - dev  # branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # java version
          distribution: 'temurin'  # JDK distribution


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew  # set permissions

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
