name: Android CI

on: 
  push:
    branches:
      - master  # main branch name
  pull_request:
    branches:
      - master  # main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  # java version

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test